;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Event.Hitstop",NewTagName="Event.HitImpact")
+GameplayTagList=(Tag="Ability.Combo.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.HitReaction",DevComment="")
+GameplayTagList=(Tag="Ability.TargetLock",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Input",DevComment="")
+GameplayTagList=(Tag="Event.Combo.WindowClose",DevComment="")
+GameplayTagList=(Tag="Event.Combo.WindowOpen",DevComment="")
+GameplayTagList=(Tag="Event.Hit.Melee",DevComment="")
+GameplayTagList=(Tag="Event.HitImpact",DevComment="")
+GameplayTagList=(Tag="Event.TargetLock.Unlock",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Locked",DevComment="")

